platform/core/acl/routes/web.php
<?php

use Trivium\ACL\Http\Controllers\Auth\ForgotPasswordController;
use Trivium\ACL\Http\Controllers\Auth\LoginController;
use Trivium\ACL\Http\Controllers\Auth\ResetPasswordController;
use Trivium\ACL\Http\Middleware\CheckUserUpdatePermission;
use Trivium\Base\Facades\AdminHelper;
use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Trivium\ACL\Http\Controllers'], function () {
    AdminHelper::registerRoutes(function () {
        Route::group(['middleware' => 'guest'], function () {
            Route::get('login', [LoginController::class, 'showLoginForm'])->name('access.login');
            Route::post('login', [LoginController::class, 'login'])->name('access.login.post');

            Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])
                ->name('access.password.request');
            Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])
                ->name('access.password.email');

            Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])
                ->name('access.password.reset');
            Route::post('password/reset', [ResetPasswordController::class, 'reset'])
                ->name('access.password.reset.post');
        });
    }, ['web', 'core']);

    AdminHelper::registerRoutes(function () {
        Route::get('logout', [
            'as' => 'access.logout',
            'uses' => 'Auth\LoginController@logout',
            'permission' => false,
        ]);

        Route::group(['prefix' => 'system'], function () {
            Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
                Route::resource('', 'UserController')->except(['edit', 'update'])->parameters(['' => 'user']);

                Route::post('modify-profile-image/{user}', [
                    'as' => 'profile.image',
                    'uses' => 'UserController@postAvatar',
                    'permission' => false,
                ])->wherePrimaryKey();

                Route::post('delete-profile-image/{user}', [
                    'as' => 'profile.image.destroy',
                    'uses' => 'UserController@removeAvatar',
                    'permission' => false,
                ])->wherePrimaryKey();

                Route::middleware(CheckUserUpdatePermission::class)->group(function () {
                    Route::put('password/{user}', [
                        'as' => 'change-password',
                        'uses' => 'UserController@postChangePassword',
                        'permission' => false,
                        'middleware' => 'preventDemo',
                    ])->wherePrimaryKey('user');

                    Route::get('profile/{user}', [
                        'as' => 'profile.view',
                        'uses' => 'UserController@getUserProfile',
                        'permission' => false,
                    ])->wherePrimaryKey('user');

                    Route::put('profile/{user}', [
                        'as' => 'update-profile',
                        'uses' => 'UserController@postUpdateProfile',
                        'permission' => false,
                        'middleware' => 'preventDemo',
                    ])->wherePrimaryKey('user');

                    Route::put('profile/{user}/preferences', [
                        'as' => 'update-preferences',
                        'uses' => 'UserController@updatePreferences',
                        'permission' => false,
                        'middleware' => 'preventDemo',
                    ])->wherePrimaryKey('user');
                });

                Route::get('make-super/{user}', [
                    'as' => 'make-super',
                    'uses' => 'UserController@makeSuper',
                    'permission' => ACL_ROLE_SUPER_USER,
                ])->wherePrimaryKey('user');

                Route::get('remove-super/{user}', [
                    'as' => 'remove-super',
                    'uses' => 'UserController@removeSuper',
                    'permission' => ACL_ROLE_SUPER_USER,
                    'middleware' => 'preventDemo',
                ])->wherePrimaryKey('user');
            });

            Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {
                Route::resource('', 'RoleController')->parameters(['' => 'role']);

                Route::get('duplicate/{role}', [
                    'as' => 'duplicate',
                    'uses' => 'RoleController@getDuplicate',
                    'permission' => 'roles.create',
                ])->wherePrimaryKey('role');

                Route::get('json', [
                    'as' => 'list.json',
                    'uses' => 'RoleController@getJson',
                    'permission' => 'roles.index',
                ]);

                Route::post('assign', [
                    'as' => 'assign',
                    'uses' => 'RoleController@postAssignMember',
                    'permission' => 'roles.edit',
                ]);
            });
        });
    });
});

platform/core/acl/resources/views/users/profile/actions.blade.php
<x-core::card.footer class="bg-transparent mt-3 p-0 pt-3">
    <div class="btn-list justify-content-end">
        <x-core::button
            type="submit"
            color="primary"
            icon="ti ti-circle-check"
        >
            {{ trans('core/acl::users.update') }}
        </x-core::button>
    </div>
</x-core::card.footer>

platform/core/acl/resources/views/users/profile/base.blade.php
@extends(BaseHelper::getAdminMasterLayoutTemplate())

@section('content')
    <div class="user-profile">
        <x-core::card>
            <x-core::card.header>
                <x-core::tab class="card-header-tabs">
                    @if ($canChangeProfile)
                        <x-core::tab.item
                            :is-active="true"
                            id="profile"
                            icon="ti ti-user"
                            label="{{ trans('core/acl::users.info.title') }}"
                        />

                        <x-core::tab.item
                            id="avatar"
                            icon="ti ti-camera-selfie"
                            label="{{ trans('core/acl::users.avatar') }}"
                        />

                        <x-core::tab.item
                            id="change-password"
                            icon="ti ti-lock"
                            label="{{ trans('core/acl::users.change_password') }}"
                        />

                        <x-core::tab.item
                            id="preferences"
                            icon="ti ti-settings"
                            label="{{ trans('core/acl::users.preferences') }}"
                        />
                    @endif

                    {!! apply_filters(ACL_FILTER_PROFILE_FORM_TABS, null) !!}
                </x-core::tab>
            </x-core::card.header>

            <x-core::card.body>
                <x-core::tab.content>
                    @if ($canChangeProfile)
                        <x-core::tab.pane
                            id="profile"
                            :is-active="true"
                        >
                            {!! $form !!}
                        </x-core::tab.pane>

                        <x-core::tab.pane id="avatar">
                            <x-core::crop-image
                                :label="trans('core/acl::users.avatar')"
                                name="avatar_file"
                                :value="$user->avatar_url"
                                :action="route('users.profile.image', $user->id)"
                                :delete-action="route('users.profile.image.destroy', $user->getKey())"
                                :can-delete="$user->avatar_id"
                                rounded="pill"
                                :hidden-copper="!$canChangeProfile"
                                style="--bb-avatar-size: 10rem;"
                            />
                        </x-core::tab.pane>

                        <x-core::tab.pane id="change-password">
                            {!! $passwordForm !!}
                        </x-core::tab.pane>

                        <x-core::tab.pane id="preferences">
                            {!! $preferenceForm !!}
                        </x-core::tab.pane>
                    @endif

                    {!! apply_filters(ACL_FILTER_PROFILE_FORM_TAB_CONTENTS, null) !!}
                </x-core::tab.content>
            </x-core::card.body>
        </x-core::card>
    </div>
@endsection

@if ($canChangeProfile)
    @push('footer')
        {!! JsValidator::formRequest(Trivium\ACL\Http\Requests\UpdateProfileRequest::class, '#profile-form') !!}
        {!! JsValidator::formRequest(Trivium\ACL\Http\Requests\UpdatePasswordRequest::class, '#password-form') !!}
    @endpush
@endif